# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'airline' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for airline

  target 'airline-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'airlineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'airline-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for airline-tvOS

  target 'airline-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
